### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Klemen1337** [KenWillmott/HT1632#1]
Hi,
I tried to connect my [JY-MCU 3208](http://www.dx.com/p/jy-mcu-3208-lattice-clock-ht1632c-driver-with-mcu-support-secondary-development-104306#.V9RsZJN97fY) and arduino UNO. Sometimes the text shows up, sometimes everything just stops working and sometimes I get random leds (Its like the original clock code is trying to show the time). Do you have any ideas why that would happen?

Cheers 🍺 ,
Klemen

This is the code that I am using for testing.

```
#include <HT1632.h>
HT1632Class LEDmatrix;

void setup() {
  //initialize the display
  LEDmatrix.begin(8, 9, 10);  // CS, WR, DATA
}

void loop()
{
  LEDmatrix.setBrightness(2);
  LEDmatrix.clear();
  LEDmatrix.printString("Test");
  delay(1000);
}
```

**Comment by KenWillmott** [comment]
The most likely explanation is that you have not succeeded in grounding the RESET pin on the ICSP connector on the display PCB. In that case, the onboard AVR is running, which will interfere with external controlling signals.

**Comment by Klemen1337** [comment]
I belive I have an older version of the board (its not PRO). Would that make a difference?

**Comment by KenWillmott** [comment]
This software does not support the older version of the board.
